### ISSUE TITLE
I'm encountering the below error, can you assist?  

### ISSUE THREAD

**Issue by oasec1** [Cyb3rM0nk3y/DefensiveSysmon#1]
First, this is an awesome powershell script, thank you for sharing your work. 
I believe it could be caused because the process its trying to capture is closing too fast.  Is it possible to add the following, right  after the program start, collect and export a list of the running processes to a csv including name and process id and export it? Another thought might to be to open a csv file after execution that continuously appends the processes that its captured, including name and process id.

Windows PowerShell transcript start
Start time: 20201216150853
Username: EesssM\joe1
RunAs User: EesssM\joe1
Configuration Name: 
Machine: EesssM (Microsoft Windows NT 10.0.18362.0)
Host Application: powershell.exe -ExecutionPolicy Bypass -File c:\ztools\DumpProcess.ps1
Process ID: 7024
PSVersion: 5.1.18362.145
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.145
BuildVersion: 10.0.18362.145
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
**********************
Command start time: 20201216150854
**********************
PS>CommandInvocation(Out-String): "Out-String"
>> ParameterBinding(Out-String): name="InputObject"; value="Cannot find a process with the process identifier 368."
Get-Process : Cannot find a process with the process identifier 368.
At C:\ztools\DumpProcess.ps1:120 char:31
+        Out-Minidump -Process (Get-Process -Id $process)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (368:Int32) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand
Get-Process : Cannot find a process with the process identifier 368.
At C:\ztools\DumpProcess.ps1:120 char:31
+        Out-Minidump -Process (Get-Process -Id $process)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (368:Int32) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand
Get-Process : Cannot find a process with the process identifier 368.
At C:\ztools\DumpProcess.ps1:120 char:31
+        Out-Minidump -Process (Get-Process -Id $process)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (368:Int32) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Commands.GetProcessCommand

**********************
Command start time: 20201216150854
**********************
PS>TerminatingError(Out-Minidump): "Cannot bind argument to parameter 'Process' because it is null."

**Comment by Cyb3r-Monk** [comment]
Thanks! 
Sorry, I destroyed the lab environment a while ago. As you said, if you do a test with a few files, the process exits so quickly and you get the error. I would query the event log to get process Id via Event Viewer or PowerShell.
